# Generated by Django 5.0.4 on 2024-07-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_driver_drivinglicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglicense',
            old_name='licence_number',
            new_name='license_number',
        ),
    ]
