# Generated by Django 5.0.4 on 2024-07-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_menureview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menureview',
            options={'verbose_name': 'Menu Review', 'verbose_name_plural': 'Menu Reviews'},
        ),
    ]
