# Generated by Django 5.0.4 on 2024-07-10 22:28

from django.db import migrations


def set_item_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    items = item.objects.all()

    for i in items:
        if i.price <= 10:
            i.rarity = 'Rare'
        elif i.price <= 20:
            i.rarity = 'Very Rare'
        elif i.price <= 30:
            i.rarity = 'Extremely Rare'
        else:
            i.rarity = 'Mega Rare'
        i.save()


def reverse_set_item_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    items = item.objects.all()

    for i in items:
        i.rarity = item._meta.get_field('rarity').default
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_item_rarity, reverse_code=reverse_set_item_rarity)
    ]