# Generated by Django 5.0.4 on 2024-07-12 14:31

from django.db import migrations


def set_new_price(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone.objects.all()

    for sm in smartphones:
        sm.price = len(sm.brand) * 120
        sm.save()


def reverse_set_new_price(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone.objects.all()

    for sm in smartphones:
        sm.price = sm._meta.get_field('price').default
        sm.save()


def set_category(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone.objects.all()

    for sm in smartphones:
        if sm.price >= 750:
            sm.category = "Expensive"
        else:
            sm.category = "Cheap"
        sm.save()


def reverse_set_category(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone.objects.all()

    for sm in smartphones:
        sm.category = sm._meta.get_field('category').default
        sm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_new_price, reverse_code=reverse_set_new_price),
        migrations.RunPython(set_category, reverse_code=reverse_set_category)
    ]
