# Generated by Django 5.0.4 on 2024-07-12 14:44

from django.db import migrations
from django.utils import timezone


def set_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')
    orders = order.objects.all()

    for o in orders:
        if o.status == 'Pending':
            o.delivery = o.order_date + timezone.timedelta(days=3)
        elif o.status == 'Completed':
            o.warranty = "24 months"
        elif o.status == "Cancelled":
            o.delete()


def reverse_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')
    orders = order.objects.all()

    for o in orders:
        if o.status == 'Pending':
            o.delivery = None
        elif o.status == 'Completed':
            o.warranty = o._meta.get_field('warranty').default

        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_and_warranty, reverse_code=reverse_delivery_and_warranty)
    ]
